// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbtOqUC-QNEr1QTonAH2TKz__aDaykeM8',
    appId: '1:69341000932:web:36f0a060969d8a0fd028f1',
    messagingSenderId: '69341000932',
    projectId: 'es-pi3-2026-t1-g24',
    authDomain: 'es-pi3-2026-t1-g24.firebaseapp.com',
    storageBucket: 'es-pi3-2026-t1-g24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGNJJMZ0-tyL-0W-s8H-p_RH4jEZtazD4',
    appId: '1:69341000932:android:647d428747e7f7cfd028f1',
    messagingSenderId: '69341000932',
    projectId: 'es-pi3-2026-t1-g24',
    storageBucket: 'es-pi3-2026-t1-g24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0VIfZqMkaBla0o_n0l_fHXQCyXLmbiHY',
    appId: '1:69341000932:ios:ede95b06d545ba44d028f1',
    messagingSenderId: '69341000932',
    projectId: 'es-pi3-2026-t1-g24',
    storageBucket: 'es-pi3-2026-t1-g24.firebasestorage.app',
    iosBundleId: 'br.edu.puccampinas.mesclaInvest',
  );
}
